import { Inter } from "next/font/google";
import "./globals.scss";
import classes from './indexpage.modules.scss'
import NavAuth from "@/components/navigation/navAuth";
import AuthPopUp from "@/components/auth/authPopup";
import { getSession } from "@/lib/auth/tokenHandler";
import SessionAuth from "@/components/navigation/sessionNav";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children  }) {

  const session = await getSession();


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bodywrapper">
          <div className="navigation"></div>

          <h3 id="main-logo">WeRead</h3>

          <form>
            <input type="text" name="search" placeholder="Search for Books" />
          </form>

          <nav className="navItem">
            {!session && <NavAuth />}
            {session && <SessionAuth />}
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
