import { Inter } from "next/font/google";
import "./globals.scss";
import classes from './indexpage.modules.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  console.log(classes)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bodywrapper">
          <div className="navigation"></div>

          <nav className="navItem">
            <h3>WeRead</h3>
            <ul>
              <li>Login</li>
              <li>Register</li>
            </ul>
          </nav>

          {children}
        </div>
      </body>
    </html>
  );
}
