import { Inter } from "next/font/google";
import "./globals.scss";
import classes from './indexpage.modules.scss'
import NavAuth from "@/components/navigation/navAuth";
import AuthPopUp from "@/components/auth/authPopup";
import { getSession } from "@/lib/auth/tokenHandler";
import SessionAuth from "@/components/navigation/sessionNav";
import { runBookSearch } from "@/lib/search/search";
import NavSearch from "@/components/navigation/navSearch";
import Link from "next/link";
import UnAuthHome from "@/components/home/unAuthHome";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children  }) {

  const session = await getSession();


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bodywrapper">
          <div className="navigation"></div>
          <Link href={"/"} id="main-logo">
            <h3>WeRead</h3>
          </Link>

          {session && <NavSearch />}

          {!session && (
            <nav className="navItem nav-item-un-auth">
              <NavAuth />
            </nav>
          )}

          {session && (
            <nav className="navItem nav-item-auth">
              <SessionAuth />
            </nav>
          )}
          
          {children}
        </div>
      </body>
    </html>
  );
}
